### ISSUE TITLE
v2.9.4 preparation

### ISSUE THREAD

**Issue by ddpbsd** [ossec/ossec-hids#1346]
Let's try something new. We missed a few things for 2.9.3, so maybe tracking these items in an issue will help for 2.9.4. If anything is missing, please post it so I can add it to the list.
I have branched [v2.9.4](https://github.com/ossec/ossec-hids/tree/v2.9.4) for people to test.

# Things to backport:

- [x] Pull request #1088 - fix reportd crash
- [x] Pull request #1340 - fix a time issue
- [x] Pull request #1334 - fix negating an IP address in a rule
- [x]  Pull request #1330 - fix daily reports
- [x] Missing agent.conf error

**Comment by ddpbsd** [comment]
Pull request #1350 hopefully solves the first 3 items.
The last is a bit more work, and will have to wait.

**Comment by ddpbsd** [comment]
I need to find the fix for the missing agent.conf error thing.
`ERROR: Error reading XML file '/var/ossec/etc/shared/agent.conf': XMLERR: File '/var/ossec/etc/shared/agent.conf' not found.`

**Comment by zekicker** [comment]
Same as ddpbsd.

Txs

**Comment by reyjrar** [comment]
Noticed a number of commits missing from 2.9.3 around the JSON output:

   * 5fe1c667af655725a32b152db854702873bd84bc
   * 278a66ea0d4334970a552d9d29f63bcdea9868f4
   * 7e094aeeeb1e0f55dca335cdae8237f6d50b99e3
   * 4985d87f39aafbd816e5bfbf93ee6050332c77f6

**Comment by ddpbsd** [comment]
@reyjrar were these in 2.8? I'm hoping to restrict this to bugfixes (and some of those may qualify).

**Comment by spaims** [comment]
Pull request #1205 . This might be the one you were referring to for the agent.conf error thing.

I would really love to see this fixed!

**Comment by calve** [comment]
Hi guys,

any chance we cut the 2.9.4 release in the next days/week ? May I provide any help ?

**Comment by ddpbsd** [comment]
Pull request #1413 adds:
Fix for issue #1402 
Fix for issue #1207

**Comment by billy-shears** [comment]
Please also backmerge issue #1425 fix (pull request [#1428](https://github.com/ossec/ossec-hids/pull/1428)). Thanks in advance!

**Comment by ddpbsd** [comment]
Pull request #1413 has been merged. Last call for 2.9.4 stuff.

**Comment by ddpbsd** [comment]
Oh, and testing would be great. I don't have any 2.9.x systems.
